name: Jvm-Utilities

on:
    release:
        types: [ created ]

jobs:
    build:

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'microsoft'
                    server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                    settings-path: ${{ github.workspace }} # location for the settings.xml file

            -   name: Gradlew executable
                run: chmod +x ./gradlew

            -   name: Build with Gradle
                uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
                with:
                    arguments: build
                env:
                    OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
                    OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
                    OSSRH_PROFILE_ID: ${{secrets.OSSRH_PROFILE_ID}}
                    SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
                    SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
                    SIGNING_PGP_B64: ${{secrets.SIGNING_PGP_B64}}

            # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
            # the publishing section of your build.gradle
            -   name: Publish to GitHub Packages (jvm-utilities)
                uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
                with:
                    arguments: jvm-utilities:publishReleasePublicationToSonatypeRepository
                env:
                    OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
                    OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
                    OSSRH_PROFILE_ID: ${{secrets.OSSRH_PROFILE_ID}}
                    SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
                    SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
                    SIGNING_PGP_B64: ${{secrets.SIGNING_PGP_B64}}
#            -   name: Publish to GitHub Packages (swing-utilities)
#                uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#                with:
#                    arguments: swing-utilities:publishReleasePublicationToSonatypeRepository
#                env:
#                    OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
#                    OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
#                    OSSRH_PROFILE_ID: ${{secrets.OSSRH_PROFILE_ID}}
#                    SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
#                    SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
#                    SIGNING_PGP_B64: ${{secrets.SIGNING_PGP_B64}}